import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['200','300', '400', '500', '600', '700', '900'],
})



export const metadata: Metadata = {
  title: "Portafolio Michael Robayo-Desarrollador web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ poppins.className } dark:bg-gradient-to-r dark:from-indigo-900 dark:via-purple-900 dark:to-gray-900 bg-[#ffffff] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
